name: Scala CI

on:
  push:
    branches-ignore:
      - "update/**"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need the git history for sbt-dynver to determine the version
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
      - id: nodenv
        uses: nodenv/actions/node-version@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nodenv.outputs.node-version }}"
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/local/
            ~/.ivy2/cache/
            ~/.sbt/
            ~/.coursier/
          key: |
            ${{runner.os}}-${{hashFiles('**/build.sbt')}}
            ${{runner.os}}-
      - name: Run tests
        run: sbt test
